### ISSUE TITLE
pgmoon operations block server

### ISSUE THREAD

**Issue by daurnimator** [rokf/lua-http-blog-example#5]
Consider using https://github.com/daurnimator/cqueues-pgsql instead.

There's also https://github.com/daurnimator/lua-pg/ which can use cqueues-pgsql. This project is my playground for coming up with better postgres libraries for lua.

**Comment by rokf** [comment]
Oh, I thought that when I select `cqueues` as the socket type it shouldn't block. Didn't check what the code is actually doing behind the scenes.

Will try to port it today then ;) Thanks!

**Comment by rokf** [comment]
Ported to cqueues-pgsql (1dfd6cc29d4155f8d364f5abc56e5ee5b7c7cfe4).

**Comment by daurnimator** [comment]
Comments left on the commit.

**Comment by rokf** [comment]
Fixed and seems to be working fine (8beb0c57b12a6e3438148255afa3562c4fe04acd).

**Comment by daurnimator** [comment]
You shouldn't need that `escape` function any more :)
